services:
  - type: web
    name: food-delivery-platform
    env: node
    plan: free
    buildCommand: npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DB_PATH
        value: ./database/food_delivery.db
      - key: CORS_ORIGIN
        value: https://food-delivery-platform.onrender.com
    autoDeploy: true 